# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-24 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0007_category_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='liked',
        ),
    ]
